// Auto-generated by scripts/generate-build-info.mjs — do not edit.
export const APP_BUILD_ISO_DATE = '2026-04-06T20:04:30.071Z';
export const APP_GIT_COMMIT = "3678ea4";
export const APP_PACKAGE_VERSION = "1.3.3";
export const APP_ENV_LABEL = "development";
