// Auto-generated by scripts/generate-build-info.mjs — do not edit.
export const APP_BUILD_ISO_DATE = '2026-04-06T03:47:39.967Z';
export const APP_GIT_COMMIT = "ade56b8";
export const APP_PACKAGE_VERSION = "1.3.3";
export const APP_ENV_LABEL = "development";
